#!/usr/bin/env bash
function throttle() {
	stdbuf -oL nl | while read -r idx line; do
		echo -e "\n($idx) Throttling $(date -u)" >> /tmp/debug_chan
		echo "$line"
		sleep $1
	done
}
function look() {
	t cat
}
function t() {
	cmd="$@"
	loc="${BASH_SOURCE[1]}:${BASH_LINENO[0]}"
	"$@" | while read -r line; do
		echo "+ $loc: t $cmd" >> /tmp/debug_chan
		echo -e "\t${indent}$line" >> /tmp/debug_chan
		echo "$line"
	done
}
function d() {
	cmd="$@"
	loc="${BASH_SOURCE[1]}:${BASH_LINENO[0]}"
	"$@" | while read -r line; do
		echo "+ $loc: d $cmd" >> /tmp/debug_chan
		echo -e "\t${indent}$line" >> /tmp/debug_chan
		# d() doesn't send output to stdout, it is for debugging
		# echo "$line"
	done
}
function start_monitor() {
	rm -f /tmp/debug_chan
	mkfifo /tmp/debug_chan
	tail -f /tmp/debug_chan &
	TAIL_PID=$!
}
function stop_monitor() {
	kill $TAIL_PID
	wait
}
start_monitor
source "$1"
stop_monitor
